POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
### 
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 
###

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 
###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 
###

GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 
###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 
###


POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 

{
   "tweet": "The Mornings..."
}
###


DELETE http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjU5MTg3NjI2fQ.Xe-CLZcR8g2pzGRBeYGmjm4_HLcc0t78xITbrl2mnKU 